wa/client_app/urls.py
from django.urls import path, include
from . import views, auth_views

app_name = 'client'
urlpatterns = [
    path('', views.index, name='home'),
    path('about', views.about, name='about'),
    path('show-book/<int:pk>', views.book_info, name='book-info'),
    path('filters', views.filters, name='filters'),
    path('html', views.html_example),
    path('category-<int:pk>', views.filter_by_category),
    path('cabinet', views.cabinet, name='cabinet'),
    path('return-json', views.return_json),
    path('login', auth_views.login_, name='login'),
    path('register', auth_views.register_, name='register'),
    path('logout', auth_views.logout_, name='logout'),
    path('calculator' , views.calculator)
]

wa/wa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('client_app.urls' , namespace='client'))
]+ static(settings.STATIC_ROOT, document_root=settings.STATIC_URL)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wa/wa/templates/includes/header.html
{#<header>#}
{#    <a href="/">Home page</a>#}
{#    <a href="/about">About</a>#}
{#    <a href="#">contacts</a>#}
{#</header>#}
{% load poll_extras %}
{% get_categories as categories %}
{{ request.user }}
{% get_money_exchange_from_NBU as FX_rates %}
{#{{ FX_rates }}#}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'client:home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'client:about' %}">About</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'client:filters' %}">Фильтры</a>
                    <a class="dropdown-item" href="/html">HTML</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    FX_rates
                </a>
                <div class="dropdown-menu" style="max-height: 500px; overflow-y: auto" aria-labelledby="navbarDropdown">
                    {% for elem in FX_rates %}
                        <a class="dropdown-item">{{ elem.txt }} {{ elem.rate }} {{ elem.cc }}</a>
                    {% endfor %}

                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Category
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% for category in categories %}
                        <a class="dropdown-item" href="category-{{ category.id }}">{{ category.title }}</a>
                    {% endfor %}
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
        </ul>
        <a href="/return-json">return json object</a>
        <a class="btn btn-info" href="{% url 'client:cabinet' %}">Мой кабинет</a>

        {% if request.user.is_authenticated %}
            <a class="btn btn-success" href="{% url 'client:logout' %}">Выход({{ request.user.username }})</a>
        {% else %}
            <a href="{% url 'client:login' %}" class="btn btn-success">Вход</a>
            <a href="{% url 'client:register' %}" class="btn btn-primary">Регистрация</a>
        {% endif %}
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>